
<img src="assets/simple_neuron.png" width=400px>

 

$$
\begin{align}
y &= f(w_1 x_1 + w_2 x_2 + b) \\
y &= f\left(\sum_i w_i x_i +b \right)
\end{align}
$$


$$
h = \begin{bmatrix}
x_1 \, x_2 \cdots  x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_1 \\
           w_2 \\
           \vdots \\
           w_n
\end{bmatrix}
$$


<img src="assets/tensor_examples.svg" width=600px>



In [1]:
# First, import PyTorch
import torch

In [2]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [3]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [4]:

# Now, make our labels from our data and true weights

y = activation(torch.sum(features * weights) + bias)
y = activation((features * weights).sum() + bias)

In [6]:


y = activation(torch.mm(features, weights.view(5,1)) + bias)



<img src='assets/multilayer_diagram_weights.png' width=450px>
 

$$
\vec{h} = [h_1 \, h_2] = 
\begin{bmatrix}
x_1 \, x_2 \cdots \, x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_{11} & w_{12} \\
           w_{21} &w_{22} \\
           \vdots &\vdots \\
           w_{n1} &w_{n2}
\end{bmatrix}
$$


$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

In [7]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [8]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[ 0.3171]])


In [9]:
import numpy as np
a = np.random.rand(4,3)
a

array([[ 0.74754718,  0.67302554,  0.92897773],
       [ 0.72024925,  0.86702166,  0.44751196],
       [ 0.95402827,  0.83605644,  0.75704974],
       [ 0.96788367,  0.83609528,  0.06201498]])

In [11]:
b = torch.from_numpy(a)
b

tensor([[ 0.7475,  0.6730,  0.9290],
        [ 0.7202,  0.8670,  0.4475],
        [ 0.9540,  0.8361,  0.7570],
        [ 0.9679,  0.8361,  0.0620]], dtype=torch.float64)

In [12]:
b.numpy()

array([[ 0.74754718,  0.67302554,  0.92897773],
       [ 0.72024925,  0.86702166,  0.44751196],
       [ 0.95402827,  0.83605644,  0.75704974],
       [ 0.96788367,  0.83609528,  0.06201498]])

In [13]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[ 1.4951,  1.3461,  1.8580],
        [ 1.4405,  1.7340,  0.8950],
        [ 1.9081,  1.6721,  1.5141],
        [ 1.9358,  1.6722,  0.1240]], dtype=torch.float64)

In [14]:
# Numpy array matches new values from Tensor
a

array([[ 1.49509436,  1.34605107,  1.85795546],
       [ 1.44049849,  1.73404332,  0.89502392],
       [ 1.90805655,  1.67211288,  1.51409948],
       [ 1.93576734,  1.67219056,  0.12402995]])